version: "3"

services:
    '2022':
        build:
            context: .
            dockerfile: Dockerfile
        container_name: '2022'
        image: nacho/2021
        ports:
            - '86:80'
        volumes: 
            - ./:/var/www/html